
	import fedreg.core.*

	/*
	 Initial attribute definition and population for Federation Registry
	*/
	
	def coreCategory = new AttributeCategory(name:'Core').save()
	def optionalCategory = new AttributeCategory(name:'Optional').save()
	
	def o = new AttributeBase(oid: , name: , friendlyName: , headerName: , alias:, description:, scope:coreCategory, specificationRequired:false)
	def ou =  new AttributeBase(oid:'2.5.4.11', name:'urn:mace:dir:attribute-def:ou', friendlyName:'Organizational Unit', headerName:'Shib-Person-ou', alias:'ou', description:'OrganizationalUnit currently used for faculty membership of staff', scope:optionalCategory, specificationRequired:false)
	def postalAddress =  new AttributeBase(oid:'2.5.4.16', name:'urn:mace:dir:attribute-def:postalAddress', friendlyName:'Business postal address', headerName:'Shib-OrgPerson-postalAddress', alias:'postalAddress', description:'Business postal address: Campus or office address', scope:optionalCategory, specificationRequired:false)
	
	def auEduPersonSharedToken =  new AttributeBase(oid:'1.3.6.1.4.1.27856.1.2.5', name:'urn:oid:1.3.6.1.4.1.27856.1.2.5', friendlyName:'Shared Token', headerName:'Shib-AEP-SharedToken', alias:'auEduPersonSharedToken', description:'A unique identifier enabling federation spanning services such as Grid and Repositories', scope:coreCategory, specificationRequired:false)
	def auEduPersonAffiliation =  new AttributeBase(oid:'1.3.6.1.4.1.27856.1.2.1', name:'urn:oid:1.3.6.1.4.1.27856.1.2.1', friendlyName:'AU Affiliation', headerName:'Shib-AEP-Affiliation', alias:'auEduPersonAffiliation', description:'Specifies a persons relationship to the institution in broad categories but with a finer-grained set of permissible values than eduPersonAffiliation.', scope:optionalCategory, specificationRequired:false)
	def auEduPersonLegalName =  new AttributeBase(oid:'1.3.6.1.4.1.27856.1.2.2', name:'urn:oid:1.3.6.1.4.1.27856.1.2.2', friendlyName:'Legal Name', headerName:'Shib-AEP-LegalName', alias:'auEduPersonLegalName', description:'The users legal name, as per their passport, birth certificate, or other legal document', scope:optionalCategory, specificationRequired:false)
	
	def eduPersonTargetedID =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.10', name:'urn:mace:dir:attribute-def:eduPersonTargetedID', friendlyName:'Targeted ID', headerName:'persistent-id', alias:'eduPersonTargetedID', description:'A persistent, non-reassigned, privacy-preserving identifier for a principal shared between a pair of coordinating entities', scope:coreCategory, specificationRequired:false)
	def eduPersonAffiliation =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.1', name:'urn:mace:dir:attribute-def:eduPersonAffiliation', friendlyName:'Affiliation', headerName:'Shib-EP-Affiliation', alias:'eduPersonAffiliation', description:'Specifies the persons relationship(s) to the institution in broad categories such as student, faculty, staff, alum, etc.', scope:coreCategory, specificationRequired:false)
	def eduPersonOrgDN =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.3', name:'urn:mace:dir:attribute-def:eduPersonOrgDN', friendlyName:'Organization path', headerName:'Shib-EP-OrgDN', alias:'orgDN', description:'Organization path: The distinguished name (DN) of the directory entry representing the organization with which the person is associated', scope:optionalCategory, specificationRequired:false)
	def eduPersonOrgUnitDN =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.4', name:'urn:mace:dir:attribute-def:eduPersonOrgUnitDN', friendlyName:'Organizational unit path', headerName:'Shib-EP-OrgUnitDN', alias:'orgUnitDN', description:'Organization unit path: The distinguished name (DN) of the directory entries representing the persons Organizational Unit(s)', scope:optionalCategory, specificationRequired:false)
	def eduPersonEntitlement =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.7', name:'urn:mace:dir:attribute-def:eduPersonEntitlement', friendlyName:'Entitlement', headerName:'Shib-EP-Entitlement', alias:'entitlement', description:'Member of: URI (either URL or URN) that indicates a set of rights to specific resources based on an agreement across the releavant community', scope:coreCategory, specificationRequired:false)
	def eduPersonPrincipalName =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.6', name:'urn:mace:dir:attribute-def:eduPersonPrincipalName', friendlyName:'Principal Name', headerName:'Shib-EP-PrincipalName', alias:'principalName', description:'eduPerson per Internet2 and EDUCAUSE see &lt;http://www.nmi-edit.org/eduPerson/draft-internet2-mace(...)', scope:optionalCategory, specificationRequired:false)
	def eduPersonAssurance =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.11', name:'urn:mace:dir:attribute-def:eduPersonAssurance', friendlyName:'Assurance Level', headerName:'Shib-EP-Assurance', alias:'eduPersonAssurance', description:'This attribute represents identity assurance profiles (IAPs), which are the set of standards that are met by an identity assertion, based on the Identity Providers identity management processes, type of auth credential used, binding strength,  etc.', scope:coreCategory, specificationRequired:false)
	def eduPersonScopedAffiliation =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.9', name:'urn:mace:dir:attribute-def:eduPersonScopedAffiliation', friendlyName:'eduPersonScopedAffiliation', headerName:'Shib-Scoped-Affiliation', alias:'eduPersonScopedAffiliation', description:'This attribute enables an organisation to assert its relationship with the user.', scope:coreCategory, specificationRequired:false)
	def eduPersonPrimaryAffiliation =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.5', name:'urn:mace:dir:attribute-def:eduPersonPrimaryAffiliation', friendlyName:'Primary Affiliation', headerName:'Shib-EP-PrimaryAffiliation', alias:'eduPersonPrimaryAffiliation', description:'Specifies the persons PRIMARY relationship to the institution in broad categories such as student, faculty, staff, alum, etc.', scope:optionalCategory, specificationRequired:false)
	
	def cn =  new AttributeBase(oid:'2.5.4.3', name:'urn:mace:dir:attribute-def:cn', friendlyName:'cn', headerName:'Shib-Person-cn', alias:'cn', description:'An individuals common name, typically their full name. This attribute should not be used in transactions where it is desirable to maintain user anonymity.', scope:coreCategory, specificationRequired:false)
	def sn =  new AttributeBase(oid:'2.5.4.4', name:'urn:mace:dir:attribute-def:sn', friendlyName:'Surname', headerName:'Shib-Person-surname', alias:'surname', description:'Surname or family name', scope:optionalCategory, specificationRequired:false)
	def givenName =  new AttributeBase(oid:'2.5.4.42', name:'urn:mace:dir:attribute-def:givenName', friendlyName:'Given name', headerName:'Shib-InetOrgPerson-givenName', alias:'givenName', description:'Given name of a person', scope:optionalCategory, specificationRequired:false)
	def displayName =  new AttributeBase(oid:'2.16.840.1.113730.3.1.241', name:'urn:mace:dir:attribute-def:displayName', friendlyName:'Display Name', headerName:'Shib-InetOrgPerson-displayName', alias:'displayName', description:'Preferred name of a person to be used when displaying entries. This attribute should not be used in transactions where it is desirable to maintain user anonymity.', scope:coreCategory, specificationRequired:false)
	
	def mail =  new AttributeBase(oid:'0.9.2342.19200300.100.1.3', name:'urn:mace:dir:attribute-def:mail', friendlyName:'EMail', headerName:'Shib-InetOrgPerson-mail', alias:'mail', description:'E-Mail: Preferred address for e-mail to be sent to this person', scope:coreCategory, specificationRequired:false)
	def homePostalAddress =  new AttributeBase(oid:'0.9.2342.19200300.100.1.39', name:'urn:mace:dir:attribute-def:homePostalAddress', friendlyName:'Home postal address', headerName:'Shib-InetOrgPerson-homePostalAddress', alias:'homePostalAddress', description:'Home postal address: Home address of the user', scope:optionalCategory, specificationRequired:false)
	def homePhone =  new AttributeBase(oid:'0.9.2342.19200300.100.1.20', name:'urn:mace:dir:attribute-def:homePhone', friendlyName:'Private phone number', headerName:'Shib-InetOrgPerson-homePhone', alias:'homePhone', description:'Private phone number', scope:optionalCategory, specificationRequired:false)
	def telephoneNumber =  new AttributeBase(oid:'2.5.4.20', name:'urn:mace:dir:attribute-def:telephoneNumber', friendlyName:'Business phone number', headerName:'Shib-Person-telephoneNumber', alias:'telephoneNumber', description:'Office or campus phone number of the individual', scope:optionalCategory, specificationRequired:false)
	def mobile =  new AttributeBase(oid:'0.9.2342.19200300.100.1.41', name:'urn:mace:dir:attribute-def:mobile', friendlyName:'Mobile phone number', headerName:'Shib-InetOrgPerson-mobile', alias:'mobile', description:'Mobile phone number', scope:optionalCategory, specificationRequired:false)
	
	def employeeNumber =  new AttributeBase(oid:'2.16.840.1.113730.3.1.3', name:'urn:mace:dir:attribute-def:employeeNumber', friendlyName:'Employee number', headerName:'Shib-InetOrgPerson-employeeNumber', alias:'employeeNumber', description:'Identifies an employee within an organization', scope:optionalCategory, specificationRequired:false)
	def preferredLanguage =  new AttributeBase(oid:'2.16.840.1.113730.3.1.39', name:'urn:mace:dir:attribute-def:preferredLanguage', friendlyName:'Preferred Language', headerName:'Shib-InetOrgPerson-preferredLanguage', alias:'preferredLanguage', description:'Preferred written or spoken language for a person', scope:optionalCategory, specificationRequired:false)
	def userSMIMECertificate =  new AttributeBase(oid:'2.16.840.1.113730.3.1.40', name:'urn:mace:dir:attribute-def:userSMIMECertificate', friendlyName:'User S/MIME Certificate', headerName:'Shib-InetOrgPerson-userSMIMECertificate', alias:'userSMIMECertificate', description:'An X.509 certificate specifically for use in S/MIME applications (see RFCs 2632, 2633 and 2634).', scope:optionalCategory, specificationRequired:false)
	def locality =  new AttributeBase(oid:'2.5.4.7', name:'urn:mace:dir:attribute-def:locality', friendlyName:'Locality', headerName:'Shib-Locality', alias:'Locality', description:'Identifies the county, city, or other geographical area in which the entry is located or with which it is in some other way associated', scope:optionalCategory, specificationRequired:false)
	def topLevelOrg =  new AttributeBase(oid:'2.5.4.10', name:'urn:mace:dir:attribute-def:TopLevelOrg', friendlyName:'Top-level Organisation', headerName:'Shib-inetOrgPerson-TopLevelOrg', alias:'topLevelOrg', description:'Standard name of the top-level organization (institution) with which this person is associated.', scope:optionalCategory, specificationRequired:false)
	def userCertificate =  new AttributeBase(oid:'2.5.4.36', name:'urn:mace:dir:attribute-def:userCertificate', friendlyName:'User Certificate', headerName:'Shib-inetOrgPerson-userCertificate', alias:'userCertificate', description:'A users X.509 certificate', scope:optionalCategory, specificationRequired:false)
	
	// SCHAC ?
	def schacGender =  new AttributeBase(oid:'1.3.6.1.4.1.25178.1.2.2', name:'urn:oid:1.3.6.1.4.1.25178.1.2.2', friendlyName:'Gender', headerName:'Shib-schac-Gender', alias:'schacGender', description:'The state of being male or female. The gender attribute specifies the legal gender of the subject it is associated with.', scope:optionalCategory, specificationRequired:false)
	def schacPersonalTitle =  new AttributeBase(oid:'1.3.6.1.4.1.25178.1.2.8', name:'urn:oid:1.3.6.1.4.1.25178.1.2.8', friendlyName:'Personal Title', headerName:'Shib-schac-PersonalTitle', alias:'schacPersonalTitle', description:'The Personal Title attribute type specifies a personal title or salutation for a person. Examples of personal titles are Ms, Dr, Prof, Rev and Sr', scope:optionalCategory, specificationRequired:false)
	def schacUserPresenceID =  new AttributeBase(oid:'1.3.6.1.4.1.25178.1.2.12', name:'urn:oid:1.3.6.1.4.1.25178.1.2.12', friendlyName:'User Presence ID', headerName:'Shib-schac-UserPresenceID', alias:'schacUserPresenceID', description:'To store a set of values related to network presence protocols.', scope:optionalCategory, specificationRequired:false)
	def schacPersonalUniqueCode =  new AttributeBase(oid:'1.3.6.1.4.1.25178.1.2.14', name:'urn:oid:1.3.6.1.4.1.25178.1.2.14', friendlyName:'Personal Unique Code', headerName:'Shib-schac-PersonalUniqueCode', alias:'schacPersonalUniqueCode', description:'Specifies a unique code for the subject it is associated with. Its value does not necessarily correspond to any identifier outside the scope of the directories using this schema. This might be Student number, Employee number, ...', scope:optionalCategory, specificationRequired:false)
	def homeOrganization =  new AttributeBase(oid:'1.3.6.1.4.1.25178.1.2.9', name:'urn:oid:1.3.6.1.4.1.25178.1.2.9', friendlyName:'Home Organization', headerName:'Shib-HomeOrganization', alias:'homeOrganization', description:'Users Home Organization', scope:optionalCategory, specificationRequired:false)
	def homeOrganizationType =  new AttributeBase(oid:'1.3.6.1.4.1.25178.1.2.10', name:'urn:oid:1.3.6.1.4.1.25178.1.2.10', friendlyName:'Home Organization Type', headerName:'Shib-HomeOrganizationType', alias:'homeOrganizationType', description:'Type of Organization the user belongs too', scope:optionalCategory, specificationRequired:false)
	