
	import fedreg.core.*

	/*
	 Initial attribute definition and population for Federation Registry
	*/
	
	def coreCategory = new AttributeCategory(name:'Core').save()
	def optionalCategory = new AttributeCategory(name:'Optional').save()
	
	def o = new AttributeBase(oid:'2.5.4.10', name:'urn:mace:dir:attribute-def:o' , friendlyName:'Organization Name' ,scope:optionalCategory, alias:'organizationName', description:'Standard name of the top-level organization (institution) with which the user is associated.', scope:coreCategory, specificationRequired:false)
	def ou =  new AttributeBase(oid:'2.5.4.11', name:'urn:mace:dir:attribute-def:ou', friendlyName:'Organizational Unit',scope:optionalCategory, alias:'ou', description:'OrganizationalUnit currently used for faculty membership of staff', scope:optionalCategory, specificationRequired:false)
	def postalAddress =  new AttributeBase(oid:'2.5.4.16', name:'urn:mace:dir:attribute-def:postalAddress', friendlyName:'Business postal address',scope:optionalCategory, alias:'postalAddress', description:'Business postal address: Campus or office address', scope:optionalCategory, specificationRequired:false)
	
	def auEduPersonSharedToken =  new AttributeBase(oid:'1.3.6.1.4.1.27856.1.2.5', name:'urn:oid:1.3.6.1.4.1.27856.1.2.5', friendlyName:'Shared Token',scope:optionalCategory, alias:'auEduPersonSharedToken', description:'A unique identifier enabling federation spanning services such as Grid and Repositories', scope:coreCategory, specificationRequired:false)
	def auEduPersonAffiliation =  new AttributeBase(oid:'1.3.6.1.4.1.27856.1.2.1', name:'urn:oid:1.3.6.1.4.1.27856.1.2.1', friendlyName:'AU Affiliation',scope:optionalCategory, alias:'auEduPersonAffiliation', description:'Specifies a persons relationship to the institution in broad categories but with a finer-grained set of permissible values than eduPersonAffiliation.', scope:optionalCategory, specificationRequired:false)
	def auEduPersonLegalName =  new AttributeBase(oid:'1.3.6.1.4.1.27856.1.2.2', name:'urn:oid:1.3.6.1.4.1.27856.1.2.2', friendlyName:'Legal Name',scope:optionalCategory, alias:'auEduPersonLegalName', description:'The users legal name, as per their passport, birth certificate, or other legal document', scope:optionalCategory, specificationRequired:false)
	
	def eduPersonTargetedID =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.10', name:'urn:mace:dir:attribute-def:eduPersonTargetedID', friendlyName:'Targeted ID',scope:optionalCategory, alias:'eduPersonTargetedID', description:'A persistent, non-reassigned, privacy-preserving identifier for a principal shared between a pair of coordinating entities', scope:coreCategory, specificationRequired:false)
	def eduPersonAffiliation =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.1', name:'urn:mace:dir:attribute-def:eduPersonAffiliation', friendlyName:'Affiliation',scope:optionalCategory, alias:'eduPersonAffiliation', description:'Specifies the persons relationship(s) to the institution in broad categories such as student, faculty, staff, alum, etc.', scope:coreCategory, specificationRequired:false)
	def eduPersonEntitlement =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.7', name:'urn:mace:dir:attribute-def:eduPersonEntitlement', friendlyName:'Entitlement',scope:optionalCategory, alias:'entitlement', description:'Member of: URI (either URL or URN) that indicates a set of rights to specific resources based on an agreement across the releavant community', scope:coreCategory, specificationRequired:false)
	def eduPersonPrincipalName =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.6', name:'urn:mace:dir:attribute-def:eduPersonPrincipalName', friendlyName:'Principal Name',scope:optionalCategory, alias:'principalName', description:'eduPerson per Internet2 and EDUCAUSE see &lt;http://www.nmi-edit.org/eduPerson/draft-internet2-mace(...)', scope:optionalCategory, specificationRequired:false)
	def eduPersonAssurance =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.11', name:'urn:mace:dir:attribute-def:eduPersonAssurance', friendlyName:'Assurance Level',scope:optionalCategory, alias:'eduPersonAssurance', description:'This attribute represents identity assurance profiles (IAPs), which are the set of standards that are met by an identity assertion, based on the Identity Providers identity management processes, type of auth credential used, binding strength,  etc.', scope:coreCategory, specificationRequired:false)
	def eduPersonScopedAffiliation =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.9', name:'urn:mace:dir:attribute-def:eduPersonScopedAffiliation', friendlyName:'eduPersonScopedAffiliation',scope:optionalCategory, alias:'eduPersonScopedAffiliation', description:'This attribute enables an organisation to assert its relationship with the user.', scope:coreCategory, specificationRequired:false)
	def eduPersonPrimaryAffiliation =  new AttributeBase(oid:'1.3.6.1.4.1.5923.1.1.1.5', name:'urn:mace:dir:attribute-def:eduPersonPrimaryAffiliation', friendlyName:'Primary Affiliation',scope:optionalCategory, alias:'eduPersonPrimaryAffiliation', description:'Specifies the persons PRIMARY relationship to the institution in broad categories such as student, faculty, staff, alum, etc.', scope:optionalCategory, specificationRequired:false)
	
	def cn =  new AttributeBase(oid:'2.5.4.3', name:'urn:mace:dir:attribute-def:cn', friendlyName:'cn',scope:optionalCategory, alias:'cn', description:'An individuals common name, typically their full name. This attribute should not be used in transactions where it is desirable to maintain user anonymity.', scope:coreCategory, specificationRequired:false)
	def sn =  new AttributeBase(oid:'2.5.4.4', name:'urn:mace:dir:attribute-def:sn', friendlyName:'Surname',scope:optionalCategory, alias:'surname', description:'Surname or family name', scope:optionalCategory, specificationRequired:false)
	def givenName =  new AttributeBase(oid:'2.5.4.42', name:'urn:mace:dir:attribute-def:givenName', friendlyName:'Given name',scope:optionalCategory, alias:'givenName', description:'Given name of a person', scope:optionalCategory, specificationRequired:false)
	def displayName =  new AttributeBase(oid:'2.16.840.1.113730.3.1.241', name:'urn:mace:dir:attribute-def:displayName', friendlyName:'Display Name',scope:optionalCategory, alias:'displayName', description:'Preferred name of a person to be used when displaying entries. This attribute should not be used in transactions where it is desirable to maintain user anonymity.', scope:coreCategory, specificationRequired:false)
	
	def mail =  new AttributeBase(oid:'0.9.2342.19200300.100.1.3', name:'urn:mace:dir:attribute-def:mail', friendlyName:'EMail',scope:optionalCategory, alias:'mail', description:'E-Mail: Preferred address for e-mail to be sent to this person', scope:coreCategory, specificationRequired:false)
	def telephoneNumber =  new AttributeBase(oid:'2.5.4.20', name:'urn:mace:dir:attribute-def:telephoneNumber', friendlyName:'Business phone number',scope:optionalCategory, alias:'telephoneNumber', description:'Office or campus phone number of the individual', scope:optionalCategory, specificationRequired:false)
	def mobile =  new AttributeBase(oid:'0.9.2342.19200300.100.1.41', name:'urn:mace:dir:attribute-def:mobile', friendlyName:'Mobile phone number',scope:optionalCategory, alias:'mobile', description:'Mobile phone number', scope:optionalCategory, specificationRequired:false)
	def topLevelOrg =  new AttributeBase(oid:'2.5.4.10', name:'urn:mace:dir:attribute-def:TopLevelOrg', friendlyName:'Top-level Organisation',scope:optionalCategory, alias:'topLevelOrg', description:'Standard name of the top-level organization (institution) with which this person is associated.', scope:optionalCategory, specificationRequired:false)
	
	def homeOrganization =  new AttributeBase(oid:'1.3.6.1.4.1.25178.1.2.9', name:'urn:oid:1.3.6.1.4.1.25178.1.2.9', friendlyName:'Home Organization',scope:optionalCategory, alias:'homeOrganization', description:'Users Home Organization', scope:optionalCategory, specificationRequired:false)
	def homeOrganizationType =  new AttributeBase(oid:'1.3.6.1.4.1.25178.1.2.10', name:'urn:oid:1.3.6.1.4.1.25178.1.2.10', friendlyName:'Home Organization Type',scope:optionalCategory, alias:'homeOrganizationType', description:'Type of Organization the user belongs too', scope:optionalCategory, specificationRequired:false)
	