SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE `_group`;
DROP TABLE `_group_roles`;
DROP TABLE `_group_users`;
DROP TABLE `_role`;
DROP TABLE `_role_users`;
DROP TABLE `_user`;
DROP TABLE `_user__user`;
DROP TABLE `_user_passwd_history`;
DROP TABLE `any_uri`;
DROP TABLE `details`;
DROP TABLE `federation_provider`;
DROP TABLE `federation_provider_props`;
DROP TABLE `login_record`;
DROP TABLE `mailuri`;
DROP TABLE `profile_base`;
DROP TABLE `task_approver_groups`;
DROP TABLE `task_instance__user`;
DROP TABLE `tel_numuri`;
DROP TABLE `uri`;
DROP TABLE `url`;
DROP TABLE `urluri`;
SET FOREIGN_KEY_CHECKS = 1;