SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE `additional_metadata_location` DROP FOREIGN KEY `FKA1A840AD2493EB1B`;
ALTER TABLE `additional_metadata_location` DROP INDEX `FKA1A840AD2493EB1B`;
ALTER TABLE `additional_metadata_location` ADD COLUMN `uri` varchar(255) CHARACTER SET latin1 NOT NULL after `namespace`;
ALTER TABLE `additional_metadata_location` DROP COLUMN `uri_id`;
ALTER TABLE `artifact_resolution_service` DROP FOREIGN KEY `FKA0A175AFC6661FF9`;
ALTER TABLE `artifact_resolution_service` DROP INDEX `FKA0A175AFC6661FF9`;
ALTER TABLE `artifact_resolution_service` ADD INDEX `FKA0A175AF8EC51DE8` USING BTREE (descriptor_id);
ALTER TABLE `artifact_resolution_service` ADD CONSTRAINT `FKA0A175AF8EC51DE8` FOREIGN KEY (`descriptor_id`) REFERENCES `ssodescriptor` (`id`);
ALTER TABLE `assertion_consumer_service` DROP FOREIGN KEY `FK77B18B09A3A780BC`;
ALTER TABLE `assertion_consumer_service` DROP INDEX `FK77B18B09A3A780BC`;
ALTER TABLE `assertion_consumer_service` ADD INDEX `FK77B18B09D03EBEEB` USING BTREE (descriptor_id);
ALTER TABLE `assertion_consumer_service` ADD CONSTRAINT `FK77B18B09D03EBEEB` FOREIGN KEY (`descriptor_id`) REFERENCES `spssodescriptor` (`id`);
ALTER TABLE `assertionidrequest_service` DROP FOREIGN KEY `FK9D0DA7C8C9326391`;
ALTER TABLE `assertionidrequest_service` DROP FOREIGN KEY `FK9D0DA7C881D2AAE4`;
ALTER TABLE `assertionidrequest_service` DROP FOREIGN KEY `FK9D0DA7C822F46540`;
ALTER TABLE `assertionidrequest_service` DROP FOREIGN KEY `FK9D0DA7C81C590EA6`;
ALTER TABLE `assertionidrequest_service` DROP INDEX `FK9D0DA7C822F46540`;
ALTER TABLE `assertionidrequest_service` DROP INDEX `FK9D0DA7C881D2AAE4`;
ALTER TABLE `assertionidrequest_service` DROP INDEX `FK9D0DA7C8C9326391`;
ALTER TABLE `assertionidrequest_service` DROP INDEX `FK9D0DA7C81C590EA6`;
ALTER TABLE `assertionidrequest_service` ADD INDEX `FK9D0DA7C83887E9C2` USING BTREE (descriptor_id);
ALTER TABLE `assertionidrequest_service` ADD INDEX `FK9D0DA7C8E4B80C95` USING BTREE (descriptor_id);
ALTER TABLE `assertionidrequest_service` ADD INDEX `FK9D0DA7C8E8233295` USING BTREE (descriptor_id);
ALTER TABLE `assertionidrequest_service` ADD INDEX `FK9D0DA7C866752531` USING BTREE (descriptor_id);
ALTER TABLE `assertionidrequest_service` ADD CONSTRAINT `FK9D0DA7C83887E9C2` FOREIGN KEY (`descriptor_id`) REFERENCES `attribute_authority_descriptor` (`id`);
ALTER TABLE `assertionidrequest_service` ADD CONSTRAINT `FK9D0DA7C866752531` FOREIGN KEY (`descriptor_id`) REFERENCES `role_descriptor` (`id`);
ALTER TABLE `assertionidrequest_service` ADD CONSTRAINT `FK9D0DA7C8E4B80C95` FOREIGN KEY (`descriptor_id`) REFERENCES `pdpdescriptor` (`id`);
ALTER TABLE `assertionidrequest_service` ADD CONSTRAINT `FK9D0DA7C8E8233295` FOREIGN KEY (`descriptor_id`) REFERENCES `idpssodescriptor` (`id`);
ALTER TABLE `attribute` DROP FOREIGN KEY `FKC7AA9CB4F6E596`;
ALTER TABLE `attribute` DROP FOREIGN KEY `FKC7AA9C914409EA`;
ALTER TABLE `attribute` DROP FOREIGN KEY `FKC7AA9C7CB566F2`;
ALTER TABLE `attribute` DROP FOREIGN KEY `FKC7AA9C59B2AE06`;
ALTER TABLE `attribute` DROP INDEX `FKC7AA9C914409EA`;
ALTER TABLE `attribute` DROP INDEX `FKC7AA9C7CB566F2`;
ALTER TABLE `attribute` DROP INDEX `FKC7AA9CB4F6E596`;
ALTER TABLE `attribute` DROP INDEX `FKC7AA9C59B2AE06`;
ALTER TABLE `attribute` ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `attribute` ADD INDEX `FKC7AA9C2211ABF5` USING BTREE (base_id);
ALTER TABLE `attribute` ADD INDEX `FKC7AA9CA157505` USING BTREE (attribute_consuming_service_id);
ALTER TABLE `attribute` ADD INDEX `FKC7AA9CEC0AED23` USING BTREE (attribute_authority_descriptor_id);
ALTER TABLE `attribute` ADD INDEX `FKC7AA9CF794919B` USING BTREE (idpssodescriptor_id);
ALTER TABLE `attribute` ADD CONSTRAINT `FKC7AA9C2211ABF5` FOREIGN KEY (`base_id`) REFERENCES `attribute_base` (`id`);
ALTER TABLE `attribute` ADD CONSTRAINT `FKC7AA9CA157505` FOREIGN KEY (`attribute_consuming_service_id`) REFERENCES `attribute_consuming_service` (`id`);
ALTER TABLE `attribute` ADD CONSTRAINT `FKC7AA9CEC0AED23` FOREIGN KEY (`attribute_authority_descriptor_id`) REFERENCES `attribute_authority_descriptor` (`id`);
ALTER TABLE `attribute` ADD CONSTRAINT `FKC7AA9CF794919B` FOREIGN KEY (`idpssodescriptor_id`) REFERENCES `idpssodescriptor` (`id`);
ALTER TABLE `attribute_attribute_value` DROP FOREIGN KEY `FK14CD826B86A429F1`;
ALTER TABLE `attribute_attribute_value` DROP FOREIGN KEY `FK14CD826B558C8741`;
ALTER TABLE `attribute_attribute_value` DROP INDEX `FK14CD826B558C8741`;
ALTER TABLE `attribute_attribute_value` DROP INDEX `FK14CD826B86A429F1`;
ALTER TABLE `attribute_attribute_value` ADD INDEX `FK14CD826BCA24E9E2` USING BTREE (attribute_value_id);
ALTER TABLE `attribute_attribute_value` ADD INDEX `FK14CD826B1B3DD4B0` USING BTREE (attribute_values_id);
ALTER TABLE `attribute_attribute_value` ADD CONSTRAINT `FK14CD826B1B3DD4B0` FOREIGN KEY (`attribute_values_id`) REFERENCES `attribute` (`id`);
ALTER TABLE `attribute_attribute_value` ADD CONSTRAINT `FK14CD826BCA24E9E2` FOREIGN KEY (`attribute_value_id`) REFERENCES `attribute_value` (`id`);
ALTER TABLE `attribute_authority_descriptor` DROP FOREIGN KEY `FK609A73AED15ADD11`;
ALTER TABLE `attribute_authority_descriptor` DROP FOREIGN KEY `FK609A73AE3F0CB2ED`;
ALTER TABLE `attribute_authority_descriptor` DROP INDEX `FK609A73AED15ADD11`;
ALTER TABLE `attribute_authority_descriptor` DROP INDEX `FK609A73AE3F0CB2ED`;
ALTER TABLE `attribute_authority_descriptor` ADD INDEX `FK609A73AEA55D3A9E` USING BTREE (collaborator_id);
ALTER TABLE `attribute_authority_descriptor` ADD INDEX `FK609A73AE37AB64C2` USING BTREE (entity_descriptor_id);
ALTER TABLE `attribute_authority_descriptor` ADD CONSTRAINT `FK609A73AE37AB64C2` FOREIGN KEY (`entity_descriptor_id`) REFERENCES `entity_descriptor` (`id`);
ALTER TABLE `attribute_authority_descriptor` ADD CONSTRAINT `FK609A73AEA55D3A9E` FOREIGN KEY (`collaborator_id`) REFERENCES `idpssodescriptor` (`id`);
ALTER TABLE `attribute_authority_descriptor_attribute_profiles` DROP FOREIGN KEY `FK654D0A5E7CB566F2`;
ALTER TABLE `attribute_authority_descriptor_attribute_profiles` DROP INDEX `FK654D0A5E7CB566F2`;
ALTER TABLE `attribute_authority_descriptor_attribute_profiles` ADD INDEX `FK654D0A5EEC0AED23` USING BTREE (attribute_authority_descriptor_id);
ALTER TABLE `attribute_authority_descriptor_attribute_profiles` ADD CONSTRAINT `FK654D0A5EEC0AED23` FOREIGN KEY (`attribute_authority_descriptor_id`) REFERENCES `attribute_authority_descriptor` (`id`);
ALTER TABLE `attribute_authority_descriptor_samluri` DROP FOREIGN KEY `FKA6B01E4E3688E26A`;
ALTER TABLE `attribute_authority_descriptor_samluri` DROP FOREIGN KEY `FKA6B01E4E2E1B65B`;
ALTER TABLE `attribute_authority_descriptor_samluri` DROP INDEX `FKA6B01E4E2E1B65B`;
ALTER TABLE `attribute_authority_descriptor_samluri` DROP INDEX `FKA6B01E4E3688E26A`;
ALTER TABLE `attribute_authority_descriptor_samluri` ADD INDEX `FKA6B01E4EF9BCBF99` USING BTREE (samluri_id);
ALTER TABLE `attribute_authority_descriptor_samluri` ADD INDEX `FKA6B01E4E72373C8C` USING BTREE (attribute_authority_descriptor_nameidformats_id);
ALTER TABLE `attribute_authority_descriptor_samluri` ADD CONSTRAINT `FKA6B01E4E72373C8C` FOREIGN KEY (`attribute_authority_descriptor_nameidformats_id`) REFERENCES `attribute_authority_descriptor` (`id`);
ALTER TABLE `attribute_authority_descriptor_samluri` ADD CONSTRAINT `FKA6B01E4EF9BCBF99` FOREIGN KEY (`samluri_id`) REFERENCES `samluri` (`id`);
ALTER TABLE `attribute_base` DROP FOREIGN KEY `FK8B0F5694A5C8CE6`;
ALTER TABLE `attribute_base` DROP FOREIGN KEY `FK8B0F56947688A89E`;
ALTER TABLE `attribute_base` DROP INDEX `FK8B0F5694A5C8CE6`;
ALTER TABLE `attribute_base` DROP INDEX `FK8B0F56947688A89E`;
ALTER TABLE `attribute_base` DROP INDEX `name`;
ALTER TABLE `attribute_base` CHANGE COLUMN `admin_restricted` `admin_restricted` bit(1) NOT NULL after `version`;
ALTER TABLE `attribute_base` CHANGE COLUMN `category_id` `category_id` bigint(20) NOT NULL after `admin_restricted`;
ALTER TABLE `attribute_base` CHANGE COLUMN `date_created` `date_created` datetime DEFAULT NULL after `category_id`;
ALTER TABLE `attribute_base` CHANGE COLUMN `description` `description` varchar(255) CHARACTER SET latin1 NOT NULL after `date_created`;
ALTER TABLE `attribute_base` CHANGE COLUMN `last_updated` `last_updated` datetime DEFAULT NULL after `description`;
ALTER TABLE `attribute_base` CHANGE COLUMN `legacy_name` `legacy_name` varchar(255) CHARACTER SET latin1 NOT NULL after `last_updated`;
ALTER TABLE `attribute_base` CHANGE COLUMN `name` `name` varchar(255) CHARACTER SET latin1 NOT NULL after `legacy_name`;
ALTER TABLE `attribute_base` CHANGE COLUMN `name_format_id` `name_format_id` bigint(20) NOT NULL after `name`;
ALTER TABLE `attribute_base` CHANGE COLUMN `oid` `oid` varchar(255) CHARACTER SET latin1 NOT NULL after `name_format_id`;
ALTER TABLE `attribute_base` ENGINE=`InnoDB` AUTO_INCREMENT=22 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;

ALTER TABLE `attribute_base` ADD INDEX `FK8B0F569439BC85CD` USING BTREE (name_format_id);
ALTER TABLE `attribute_base` ADD INDEX `FK8B0F56946E1CFB55` USING BTREE (category_id);
ALTER TABLE `attribute_base` ADD CONSTRAINT `FK8B0F569439BC85CD` FOREIGN KEY (`name_format_id`) REFERENCES `samluri` (`id`);
ALTER TABLE `attribute_base` ADD CONSTRAINT `FK8B0F56946E1CFB55` FOREIGN KEY (`category_id`) REFERENCES `attribute_category` (`id`);
ALTER TABLE `attribute_category` ENGINE=`InnoDB` AUTO_INCREMENT=3 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `attribute_consuming_service` DROP FOREIGN KEY `FK76FE534CA3A780BC`;
ALTER TABLE `attribute_consuming_service` DROP INDEX `FK76FE534CA3A780BC`;
ALTER TABLE `attribute_consuming_service` ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `attribute_consuming_service` ADD INDEX `FK76FE534CD03EBEEB` USING BTREE (descriptor_id);
ALTER TABLE `attribute_consuming_service` ADD CONSTRAINT `FK76FE534CD03EBEEB` FOREIGN KEY (`descriptor_id`) REFERENCES `spssodescriptor` (`id`);
ALTER TABLE `attribute_consuming_service_service_descriptions` DROP FOREIGN KEY `FKC631FC54B4F6E596`;
ALTER TABLE `attribute_consuming_service_service_descriptions` DROP INDEX `FKC631FC54B4F6E596`;
ALTER TABLE `attribute_consuming_service_service_descriptions` ADD INDEX `FKC631FC54A157505` USING BTREE (attribute_consuming_service_id);
ALTER TABLE `attribute_consuming_service_service_descriptions` ADD CONSTRAINT `FKC631FC54A157505` FOREIGN KEY (`attribute_consuming_service_id`) REFERENCES `attribute_consuming_service` (`id`);
ALTER TABLE `attribute_consuming_service_service_names` DROP FOREIGN KEY `FK9D59D58BB4F6E596`;
ALTER TABLE `attribute_consuming_service_service_names` DROP INDEX `FK9D59D58BB4F6E596`;
ALTER TABLE `attribute_consuming_service_service_names` ADD INDEX `FK9D59D58BA157505` USING BTREE (attribute_consuming_service_id);
ALTER TABLE `attribute_consuming_service_service_names` ADD CONSTRAINT `FK9D59D58BA157505` FOREIGN KEY (`attribute_consuming_service_id`) REFERENCES `attribute_consuming_service` (`id`);
ALTER TABLE `attribute_service` DROP FOREIGN KEY `FK1804BC12C9326391`;
ALTER TABLE `attribute_service` DROP INDEX `FK1804BC12C9326391`;
ALTER TABLE `attribute_service` ADD INDEX `FK1804BC123887E9C2` USING BTREE (descriptor_id);
ALTER TABLE `attribute_service` ADD CONSTRAINT `FK1804BC123887E9C2` FOREIGN KEY (`descriptor_id`) REFERENCES `attribute_authority_descriptor` (`id`);
ALTER TABLE `attribute_value` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `audit_log` ENGINE=`InnoDB` AUTO_INCREMENT=2292 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `authz_service` DROP FOREIGN KEY `FK44BD53481C590EA6`;
ALTER TABLE `authz_service` DROP INDEX `FK44BD53481C590EA6`;
ALTER TABLE `authz_service` ADD INDEX `FK44BD5348E4B80C95` USING BTREE (descriptor_id);
ALTER TABLE `authz_service` ADD CONSTRAINT `FK44BD5348E4B80C95` FOREIGN KEY (`descriptor_id`) REFERENCES `pdpdescriptor` (`id`);
ALTER TABLE `cacertificate` ENGINE=`InnoDB` AUTO_INCREMENT=46 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `cakey_info` DROP FOREIGN KEY `FKC42E70EC2590286C`;
ALTER TABLE `cakey_info` DROP INDEX `FKC42E70EC2590286C`;
ALTER TABLE `cakey_info` ENGINE=`InnoDB` AUTO_INCREMENT=46 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `cakey_info` ADD INDEX `FKC42E70ECEDEF265B` USING BTREE (certificate_id);
ALTER TABLE `cakey_info` ADD CONSTRAINT `FKC42E70ECEDEF265B` FOREIGN KEY (`certificate_id`) REFERENCES `cacertificate` (`id`);
ALTER TABLE `certificate` CHANGE COLUMN `issuer` `issuer` varchar(2048) CHARACTER SET latin1 NOT NULL after `expiry_date`;
ALTER TABLE `certificate` CHANGE COLUMN `subject` `subject` varchar(2048) CHARACTER SET latin1 NOT NULL after `last_updated`;
ALTER TABLE `certificate` ENGINE=`InnoDB` AUTO_INCREMENT=4 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `contact` DROP FOREIGN KEY `FK38B72420F6C921D`;
ALTER TABLE `contact` DROP FOREIGN KEY `FK38B72420E6E281BA`;
ALTER TABLE `contact` DROP FOREIGN KEY `FK38B72420E5FA11AA`;
ALTER TABLE `contact` DROP FOREIGN KEY `FK38B72420E13DB203`;
ALTER TABLE `contact` DROP FOREIGN KEY `FK38B72420AB4A182B`;
ALTER TABLE `contact` DROP FOREIGN KEY `FK38B724202014D46E`;
ALTER TABLE `contact` DROP INDEX `FK38B72420E13DB203`;
ALTER TABLE `contact` DROP INDEX `FK38B724202014D46E`;
ALTER TABLE `contact` DROP INDEX `FK38B72420AB4A182B`;
ALTER TABLE `contact` DROP INDEX `FK38B72420F6C921D`;
ALTER TABLE `contact` DROP INDEX `FK38B72420E6E281BA`;
ALTER TABLE `contact` DROP INDEX `FK38B72420E5FA11AA`;
ALTER TABLE `contact` ADD COLUMN `email` varchar(255) CHARACTER SET latin1 NOT NULL after `description`;
ALTER TABLE `contact` DROP COLUMN `email_id`;
ALTER TABLE `contact` ADD COLUMN `home_phone` varchar(255) CHARACTER SET latin1 DEFAULT NULL after `given_name`;
ALTER TABLE `contact` DROP COLUMN `home_phone_id`;
ALTER TABLE `contact` ADD COLUMN `mobile_phone` varchar(255) CHARACTER SET latin1 DEFAULT NULL after `last_updated`;
ALTER TABLE `contact` DROP COLUMN `mobile_phone_id`;
ALTER TABLE `contact` ADD COLUMN `secondary_email` varchar(255) CHARACTER SET latin1 DEFAULT NULL after `organization_id`;
ALTER TABLE `contact` DROP COLUMN `secondary_email_id`;
ALTER TABLE `contact` ADD COLUMN `work_phone` varchar(255) CHARACTER SET latin1 DEFAULT NULL after `surname`;
ALTER TABLE `contact` DROP COLUMN `work_phone_id`;
ALTER TABLE `contact` ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;

ALTER TABLE `contact` ADD INDEX `FK38B7242099DC19DB` USING BTREE (organization_id);
ALTER TABLE `contact` ADD CONSTRAINT `FK38B7242099DC19DB` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`id`);
ALTER TABLE `contact_person` DROP FOREIGN KEY `FKE8319054E5FA11AA`;
ALTER TABLE `contact_person` DROP FOREIGN KEY `FKE8319054E2B50CEA`;
ALTER TABLE `contact_person` DROP FOREIGN KEY `FKE8319054C365AAEA`;
ALTER TABLE `contact_person` DROP FOREIGN KEY `FKE831905422F46540`;
ALTER TABLE `contact_person` DROP FOREIGN KEY `FKE8319054190ADB79`;
ALTER TABLE `contact_person` DROP INDEX `FKE8319054E5FA11AA`;
ALTER TABLE `contact_person` DROP INDEX `FKE8319054E2B50CEA`;
ALTER TABLE `contact_person` DROP INDEX `FKE831905422F46540`;
ALTER TABLE `contact_person` DROP INDEX `FKE8319054C365AAEA`;
ALTER TABLE `contact_person` DROP INDEX `FKE8319054190ADB79`;
ALTER TABLE `contact_person` CHANGE COLUMN `organization_id` `organization_id` bigint(20) DEFAULT NULL after `last_updated`;
ALTER TABLE `contact_person` ENGINE=`InnoDB` AUTO_INCREMENT=4 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `contact_person` ADD INDEX `FKE831905499DC19DB` USING BTREE (organization_id);
ALTER TABLE `contact_person` ADD INDEX `FKE83190547F5B632A` USING BTREE (entity_id);
ALTER TABLE `contact_person` ADD INDEX `FKE831905486998819` USING BTREE (contact_id);
ALTER TABLE `contact_person` ADD INDEX `FKE831905466752531` USING BTREE (descriptor_id);
ALTER TABLE `contact_person` ADD INDEX `FKE8319054148BA99` USING BTREE (type_id);
ALTER TABLE `contact_person` ADD CONSTRAINT `FKE8319054148BA99` FOREIGN KEY (`type_id`) REFERENCES `contact_type` (`id`);
ALTER TABLE `contact_person` ADD CONSTRAINT `FKE831905466752531` FOREIGN KEY (`descriptor_id`) REFERENCES `role_descriptor` (`id`);
ALTER TABLE `contact_person` ADD CONSTRAINT `FKE83190547F5B632A` FOREIGN KEY (`entity_id`) REFERENCES `entity_descriptor` (`id`);
ALTER TABLE `contact_person` ADD CONSTRAINT `FKE831905486998819` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`id`);
ALTER TABLE `contact_person` ADD CONSTRAINT `FKE831905499DC19DB` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`id`);
ALTER TABLE `contact_type` ENGINE=`InnoDB` AUTO_INCREMENT=7 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `descriptor` ENGINE=`InnoDB` AUTO_INCREMENT=6 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `discovery_response_service` DROP FOREIGN KEY `FKF5FA366C6661FF9`;
ALTER TABLE `discovery_response_service` DROP FOREIGN KEY `FKF5FA366A3A780BC`;
ALTER TABLE `discovery_response_service` DROP INDEX `FKF5FA366C6661FF9`;
ALTER TABLE `discovery_response_service` DROP INDEX `FKF5FA366A3A780BC`;
ALTER TABLE `discovery_response_service` ADD INDEX `FKF5FA366D03EBEEB` USING BTREE (descriptor_id);
ALTER TABLE `discovery_response_service` ADD INDEX `FKF5FA3668EC51DE8` USING BTREE (descriptor_id);
ALTER TABLE `discovery_response_service` ADD CONSTRAINT `FKF5FA3668EC51DE8` FOREIGN KEY (`descriptor_id`) REFERENCES `ssodescriptor` (`id`);
ALTER TABLE `discovery_response_service` ADD CONSTRAINT `FKF5FA366D03EBEEB` FOREIGN KEY (`descriptor_id`) REFERENCES `spssodescriptor` (`id`);
ALTER TABLE `endpoint` DROP FOREIGN KEY `FK67C71D9577610032`;
ALTER TABLE `endpoint` DROP FOREIGN KEY `FK67C71D954BC7BC04`;
ALTER TABLE `endpoint` DROP FOREIGN KEY `FK67C71D952F4B1934`;
ALTER TABLE `endpoint` DROP INDEX `FK67C71D952F4B1934`;
ALTER TABLE `endpoint` DROP INDEX `FK67C71D9577610032`;
ALTER TABLE `endpoint` DROP INDEX `FK67C71D954BC7BC04`;
ALTER TABLE `endpoint` ADD COLUMN `location` varchar(255) CHARACTER SET latin1 NOT NULL after `last_updated`;
ALTER TABLE `endpoint` ADD COLUMN `response_location` varchar(255) CHARACTER SET latin1 DEFAULT NULL after `location`;
ALTER TABLE `endpoint` DROP COLUMN `location_id`;
ALTER TABLE `endpoint` DROP COLUMN `response_location_id`;
ALTER TABLE `endpoint` ENGINE=`InnoDB` AUTO_INCREMENT=8 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `endpoint` ADD INDEX `FK67C71D95EFB9933` USING BTREE (binding_id);
ALTER TABLE `endpoint` ADD CONSTRAINT `FK67C71D95EFB9933` FOREIGN KEY (`binding_id`) REFERENCES `samluri` (`id`);
ALTER TABLE `entities_descriptor` ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `entities_descriptor_entities_descriptor` DROP FOREIGN KEY `FK593DD21BB010D6CD`;
ALTER TABLE `entities_descriptor_entities_descriptor` DROP FOREIGN KEY `FK593DD21B6FA8B3E2`;
ALTER TABLE `entities_descriptor_entities_descriptor` DROP INDEX `FK593DD21BB010D6CD`;
ALTER TABLE `entities_descriptor_entities_descriptor` DROP INDEX `FK593DD21B6FA8B3E2`;
ALTER TABLE `entities_descriptor_entities_descriptor` ADD INDEX `FK593DD21B83F61353` USING BTREE (entities_descriptor_entities_descriptors_id);
ALTER TABLE `entities_descriptor_entities_descriptor` ADD INDEX `FK593DD21BC45E363E` USING BTREE (entities_descriptor_id);
ALTER TABLE `entities_descriptor_entities_descriptor` ADD CONSTRAINT `FK593DD21B83F61353` FOREIGN KEY (`entities_descriptor_entities_descriptors_id`) REFERENCES `entities_descriptor` (`id`);
ALTER TABLE `entities_descriptor_entities_descriptor` ADD CONSTRAINT `FK593DD21BC45E363E` FOREIGN KEY (`entities_descriptor_id`) REFERENCES `entities_descriptor` (`id`);
ALTER TABLE `entities_descriptor_entity_descriptor` DROP FOREIGN KEY `FKD9E0B039D15ADD11`;
ALTER TABLE `entities_descriptor_entity_descriptor` DROP FOREIGN KEY `FKD9E0B0399535300`;
ALTER TABLE `entities_descriptor_entity_descriptor` DROP INDEX `FKD9E0B039D15ADD11`;
ALTER TABLE `entities_descriptor_entity_descriptor` DROP INDEX `FKD9E0B0399535300`;
ALTER TABLE `entities_descriptor_entity_descriptor` ADD INDEX `FKD9E0B0391DA0B271` USING BTREE (entities_descriptor_entity_descriptors_id);
ALTER TABLE `entities_descriptor_entity_descriptor` ADD INDEX `FKD9E0B03937AB64C2` USING BTREE (entity_descriptor_id);
ALTER TABLE `entities_descriptor_entity_descriptor` ADD CONSTRAINT `FKD9E0B0391DA0B271` FOREIGN KEY (`entities_descriptor_entity_descriptors_id`) REFERENCES `entities_descriptor` (`id`);
ALTER TABLE `entities_descriptor_entity_descriptor` ADD CONSTRAINT `FKD9E0B03937AB64C2` FOREIGN KEY (`entity_descriptor_id`) REFERENCES `entity_descriptor` (`id`);
ALTER TABLE `entity_descriptor` DROP FOREIGN KEY `FKE5AF094BE5FA11AA`;
ALTER TABLE `entity_descriptor` DROP INDEX `FKE5AF094BE5FA11AA`;
ALTER TABLE `entity_descriptor` CHANGE COLUMN `archived` `archived` bit(1) NOT NULL after `approved`;
ALTER TABLE `entity_descriptor` CHANGE COLUMN `extensions` `extensions` varchar(2000) CHARACTER SET latin1 DEFAULT NULL after `entityid`;
ALTER TABLE `entity_descriptor` ADD INDEX `FKE5AF094B99DC19DB` USING BTREE (organization_id);
ALTER TABLE `entity_descriptor` ADD CONSTRAINT `FKE5AF094B99DC19DB` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`id`);
ALTER TABLE `entity_descriptor_additional_metadata_location` DROP FOREIGN KEY `FKC79DEB21E7E6278A`;
ALTER TABLE `entity_descriptor_additional_metadata_location` DROP FOREIGN KEY `FKC79DEB217541A908`;
ALTER TABLE `entity_descriptor_additional_metadata_location` DROP INDEX `FKC79DEB217541A908`;
ALTER TABLE `entity_descriptor_additional_metadata_location` DROP INDEX `FKC79DEB21E7E6278A`;
ALTER TABLE `entity_descriptor_additional_metadata_location` ADD INDEX `FKC79DEB214E36AF3B` USING BTREE (entity_descriptor_additional_metadata_locations_id);
ALTER TABLE `entity_descriptor_additional_metadata_location` ADD INDEX `FKC79DEB21C3F50779` USING BTREE (additional_metadata_location_id);
ALTER TABLE `entity_descriptor_additional_metadata_location` ADD CONSTRAINT `FKC79DEB214E36AF3B` FOREIGN KEY (`entity_descriptor_additional_metadata_locations_id`) REFERENCES `entity_descriptor` (`id`);
ALTER TABLE `entity_descriptor_additional_metadata_location` ADD CONSTRAINT `FKC79DEB21C3F50779` FOREIGN KEY (`additional_metadata_location_id`) REFERENCES `additional_metadata_location` (`id`);
ALTER TABLE `idpssodescriptor` DROP FOREIGN KEY `FK6BC94229D15ADD11`;
ALTER TABLE `idpssodescriptor` DROP FOREIGN KEY `FK6BC94229866C6B9A`;
ALTER TABLE `idpssodescriptor` DROP INDEX `FK6BC94229D15ADD11`;
ALTER TABLE `idpssodescriptor` DROP INDEX `FK6BC94229866C6B9A`;
ALTER TABLE `idpssodescriptor` ADD INDEX `FK6BC94229F5C1F1CB` USING BTREE (collaborator_id);
ALTER TABLE `idpssodescriptor` ADD INDEX `FK6BC9422937AB64C2` USING BTREE (entity_descriptor_id);
ALTER TABLE `idpssodescriptor` ADD CONSTRAINT `FK6BC9422937AB64C2` FOREIGN KEY (`entity_descriptor_id`) REFERENCES `entity_descriptor` (`id`);
ALTER TABLE `idpssodescriptor` ADD CONSTRAINT `FK6BC94229F5C1F1CB` FOREIGN KEY (`collaborator_id`) REFERENCES `attribute_authority_descriptor` (`id`);
ALTER TABLE `idpssodescriptor_samluri` DROP FOREIGN KEY `FKF21241C9C3B849D0`;
ALTER TABLE `idpssodescriptor_samluri` DROP FOREIGN KEY `FKF21241C93688E26A`;
ALTER TABLE `idpssodescriptor_samluri` DROP INDEX `FKF21241C9C3B849D0`;
ALTER TABLE `idpssodescriptor_samluri` DROP INDEX `FKF21241C93688E26A`;
ALTER TABLE `idpssodescriptor_samluri` ADD INDEX `FKF21241C9F9BCBF99` USING BTREE (samluri_id);
ALTER TABLE `idpssodescriptor_samluri` ADD INDEX `FKF21241C92A08D181` USING BTREE (idpssodescriptor_attribute_profiles_id);
ALTER TABLE `idpssodescriptor_samluri` ADD CONSTRAINT `FKF21241C92A08D181` FOREIGN KEY (`idpssodescriptor_attribute_profiles_id`) REFERENCES `idpssodescriptor` (`id`);
ALTER TABLE `idpssodescriptor_samluri` ADD CONSTRAINT `FKF21241C9F9BCBF99` FOREIGN KEY (`samluri_id`) REFERENCES `samluri` (`id`);
ALTER TABLE `indexed_endpoint` CHANGE COLUMN `is_default` `is_default` bit(1) NOT NULL after `samlmd_index`;
ALTER TABLE `invitation` DROP FOREIGN KEY `FK473F7799DBC6B448`;
ALTER TABLE `invitation` DROP INDEX `FK473F7799DBC6B448`;
ALTER TABLE `invitation` DROP COLUMN `grp__`;
ALTER TABLE `invitation` CHANGE COLUMN `objid` `objid` bigint(20) NOT NULL after `invite_code`;
ALTER TABLE `invitation` DROP COLUMN `perm__`;
ALTER TABLE `invitation` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `invitation` ADD INDEX `FK473F77994AC8C72C` USING BTREE (utilized_by_id);
ALTER TABLE `invitation` ADD CONSTRAINT `FK473F77994AC8C72C` FOREIGN KEY (`utilized_by_id`) REFERENCES `subject_base` (`id`);
ALTER TABLE `key_descriptor` DROP FOREIGN KEY `FK389F294FA9433291`;
ALTER TABLE `key_descriptor` DROP FOREIGN KEY `FK389F294F3257949`;
ALTER TABLE `key_descriptor` DROP FOREIGN KEY `FK389F294F13FAB137`;
ALTER TABLE `key_descriptor` DROP INDEX `FK389F294F3257949`;
ALTER TABLE `key_descriptor` DROP INDEX `FK389F294F13FAB137`;
ALTER TABLE `key_descriptor` DROP INDEX `FK389F294FA9433291`;
ALTER TABLE `key_descriptor` ENGINE=`InnoDB` AUTO_INCREMENT=4 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `key_descriptor` ADD INDEX `FK389F294FF93BA42` USING BTREE (encryption_method_id);
ALTER TABLE `key_descriptor` ADD INDEX `FK389F294F577B7128` USING BTREE (role_descriptor_id);
ALTER TABLE `key_descriptor` ADD INDEX `FK389F294FC6595678` USING BTREE (key_info_id);
ALTER TABLE `key_descriptor` ADD CONSTRAINT `FK389F294F577B7128` FOREIGN KEY (`role_descriptor_id`) REFERENCES `role_descriptor` (`id`);
ALTER TABLE `key_descriptor` ADD CONSTRAINT `FK389F294FC6595678` FOREIGN KEY (`key_info_id`) REFERENCES `key_info` (`id`);
ALTER TABLE `key_descriptor` ADD CONSTRAINT `FK389F294FF93BA42` FOREIGN KEY (`encryption_method_id`) REFERENCES `encryption_method` (`id`);
ALTER TABLE `key_info` DROP FOREIGN KEY `FK1DD9A28EE0908B8A`;
ALTER TABLE `key_info` DROP INDEX `FK1DD9A28EE0908B8A`;
ALTER TABLE `key_info` ENGINE=`InnoDB` AUTO_INCREMENT=4 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `key_info` ADD INDEX `FK1DD9A28EFF243939` USING BTREE (certificate_id);
ALTER TABLE `key_info` ADD CONSTRAINT `FK1DD9A28EFF243939` FOREIGN KEY (`certificate_id`) REFERENCES `certificate` (`id`);
ALTER TABLE `level_permission_fifth` DROP FOREIGN KEY `FKC93CB6A2D7151CB7`;
ALTER TABLE `level_permission_fifth` DROP INDEX `FKC93CB6A2D7151CB7`;
ALTER TABLE `level_permission_fifth` ADD INDEX `FKC93CB6A2251CDB71` USING BTREE (level_permission_id);
ALTER TABLE `level_permission_fifth` ADD CONSTRAINT `FKC93CB6A2251CDB71` FOREIGN KEY (`level_permission_id`) REFERENCES `permission` (`id`);
ALTER TABLE `level_permission_first` DROP FOREIGN KEY `FKC93CE39BD7151CB7`;
ALTER TABLE `level_permission_first` DROP INDEX `FKC93CE39BD7151CB7`;
ALTER TABLE `level_permission_first` ADD INDEX `FKC93CE39B251CDB71` USING BTREE (level_permission_id);
ALTER TABLE `level_permission_first` ADD CONSTRAINT `FKC93CE39B251CDB71` FOREIGN KEY (`level_permission_id`) REFERENCES `permission` (`id`);
ALTER TABLE `level_permission_fourth` DROP FOREIGN KEY `FK5EB5768FD7151CB7`;
ALTER TABLE `level_permission_fourth` DROP INDEX `FK5EB5768FD7151CB7`;
ALTER TABLE `level_permission_fourth` ADD INDEX `FK5EB5768F251CDB71` USING BTREE (level_permission_id);
ALTER TABLE `level_permission_fourth` ADD CONSTRAINT `FK5EB5768F251CDB71` FOREIGN KEY (`level_permission_id`) REFERENCES `permission` (`id`);
ALTER TABLE `level_permission_second` DROP FOREIGN KEY `FK744F50E9D7151CB7`;
ALTER TABLE `level_permission_second` DROP INDEX `FK744F50E9D7151CB7`;
ALTER TABLE `level_permission_second` ADD INDEX `FK744F50E9251CDB71` USING BTREE (level_permission_id);
ALTER TABLE `level_permission_second` ADD CONSTRAINT `FK744F50E9251CDB71` FOREIGN KEY (`level_permission_id`) REFERENCES `permission` (`id`);
ALTER TABLE `level_permission_sixth` DROP FOREIGN KEY `FKC9F42BC1D7151CB7`;
ALTER TABLE `level_permission_sixth` DROP INDEX `FKC9F42BC1D7151CB7`;
ALTER TABLE `level_permission_sixth` ADD INDEX `FKC9F42BC1251CDB71` USING BTREE (level_permission_id);
ALTER TABLE `level_permission_sixth` ADD CONSTRAINT `FKC9F42BC1251CDB71` FOREIGN KEY (`level_permission_id`) REFERENCES `permission` (`id`);
ALTER TABLE `level_permission_third` DROP FOREIGN KEY `FKCA019652D7151CB7`;
ALTER TABLE `level_permission_third` DROP INDEX `FKCA019652D7151CB7`;
ALTER TABLE `level_permission_third` ADD INDEX `FKCA019652251CDB71` USING BTREE (level_permission_id);
ALTER TABLE `level_permission_third` ADD CONSTRAINT `FKCA019652251CDB71` FOREIGN KEY (`level_permission_id`) REFERENCES `permission` (`id`);
ALTER TABLE `manage_nameidservice` DROP FOREIGN KEY `FKA253A1B5C6661FF9`;
ALTER TABLE `manage_nameidservice` DROP INDEX `FKA253A1B5C6661FF9`;
ALTER TABLE `manage_nameidservice` ADD INDEX `FKA253A1B58EC51DE8` USING BTREE (descriptor_id);
ALTER TABLE `manage_nameidservice` ADD CONSTRAINT `FKA253A1B58EC51DE8` FOREIGN KEY (`descriptor_id`) REFERENCES `ssodescriptor` (`id`);
ALTER TABLE `monitor_type` ENGINE=`InnoDB` AUTO_INCREMENT=8 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `nameidmapping_service` DROP FOREIGN KEY `FKC2051E9E81D2AAE4`;
ALTER TABLE `nameidmapping_service` DROP INDEX `FKC2051E9E81D2AAE4`;
ALTER TABLE `nameidmapping_service` ADD INDEX `FKC2051E9EE8233295` USING BTREE (descriptor_id);
ALTER TABLE `nameidmapping_service` ADD CONSTRAINT `FKC2051E9EE8233295` FOREIGN KEY (`descriptor_id`) REFERENCES `idpssodescriptor` (`id`);
ALTER TABLE `organization` DROP FOREIGN KEY `FK4644ED339E4F5455`;
ALTER TABLE `organization` DROP FOREIGN KEY `FK4644ED3324954838`;
ALTER TABLE `organization` DROP INDEX `FK4644ED3324954838`;
ALTER TABLE `organization` DROP INDEX `FK4644ED339E4F5455`;
ALTER TABLE `organization` CHANGE COLUMN `archived` `archived` bit(1) NOT NULL after `approved`;
ALTER TABLE `organization` CHANGE COLUMN `description` `description` varchar(2000) CHARACTER SET latin1 DEFAULT NULL after `date_created`;
ALTER TABLE `organization` ADD COLUMN `url` varchar(255) CHARACTER SET latin1 NOT NULL after `primary_id`;
ALTER TABLE `organization` DROP COLUMN `url_id`;
ALTER TABLE `organization` ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `organization` ADD INDEX `FK4644ED3349FDC06` USING BTREE (primary_id);
ALTER TABLE `organization` ADD CONSTRAINT `FK4644ED3349FDC06` FOREIGN KEY (`primary_id`) REFERENCES `organization_type` (`id`);
ALTER TABLE `organization_organization` DROP FOREIGN KEY `FK23F7B4BFE5FA11AA`;
ALTER TABLE `organization_organization` DROP FOREIGN KEY `FK23F7B4BF79D78378`;
ALTER TABLE `organization_organization` DROP FOREIGN KEY `FK23F7B4BF6469772B`;
ALTER TABLE `organization_organization` DROP INDEX `FK23F7B4BF79D78378`;
ALTER TABLE `organization_organization` DROP INDEX `FK23F7B4BF6469772B`;
ALTER TABLE `organization_organization` DROP INDEX `FK23F7B4BFE5FA11AA`;
ALTER TABLE `organization_organization` ADD INDEX `FK23F7B4BF99DC19DB` USING BTREE (organization_id);
ALTER TABLE `organization_organization` ADD INDEX `FK23F7B4BF184B7F5C` USING BTREE (organization_affiliates_id);
ALTER TABLE `organization_organization` ADD INDEX `FK23F7B4BF2DB98BA9` USING BTREE (organization_sponsors_id);
ALTER TABLE `organization_organization` ADD CONSTRAINT `FK23F7B4BF184B7F5C` FOREIGN KEY (`organization_affiliates_id`) REFERENCES `organization` (`id`);
ALTER TABLE `organization_organization` ADD CONSTRAINT `FK23F7B4BF2DB98BA9` FOREIGN KEY (`organization_sponsors_id`) REFERENCES `organization` (`id`);
ALTER TABLE `organization_organization` ADD CONSTRAINT `FK23F7B4BF99DC19DB` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`id`);
ALTER TABLE `organization_organization_type` DROP FOREIGN KEY `FK3217B2BAEAAD5911`;
ALTER TABLE `organization_organization_type` DROP FOREIGN KEY `FK3217B2BAA2A40630`;
ALTER TABLE `organization_organization_type` DROP FOREIGN KEY `FK3217B2BA1B0C2453`;
ALTER TABLE `organization_organization_type` DROP INDEX `FK3217B2BAA2A40630`;
ALTER TABLE `organization_organization_type` DROP INDEX `FK3217B2BA1B0C2453`;
ALTER TABLE `organization_organization_type` DROP INDEX `FK3217B2BAEAAD5911`;
ALTER TABLE `organization_organization_type` ADD INDEX `FK3217B2BA50FDE0C2` USING BTREE (organization_type_id);
ALTER TABLE `organization_organization_type` ADD INDEX `FK3217B2BACEEE2C84` USING BTREE (organization_suspensions_id);
ALTER TABLE `organization_organization_type` ADD INDEX `FK3217B2BA56860E61` USING BTREE (organization_types_id);
ALTER TABLE `organization_organization_type` ADD CONSTRAINT `FK3217B2BA50FDE0C2` FOREIGN KEY (`organization_type_id`) REFERENCES `organization_type` (`id`);
ALTER TABLE `organization_organization_type` ADD CONSTRAINT `FK3217B2BA56860E61` FOREIGN KEY (`organization_types_id`) REFERENCES `organization` (`id`);
ALTER TABLE `organization_organization_type` ADD CONSTRAINT `FK3217B2BACEEE2C84` FOREIGN KEY (`organization_suspensions_id`) REFERENCES `organization` (`id`);
ALTER TABLE `organization_type` CHANGE COLUMN `description` `description` varchar(255) CHARACTER SET latin1 NOT NULL after `date_created`;
ALTER TABLE `organization_type` ENGINE=`InnoDB` AUTO_INCREMENT=9 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;

ALTER TABLE `pdpdescriptor` DROP FOREIGN KEY `FK522A796BD15ADD11`;
ALTER TABLE `pdpdescriptor` DROP INDEX `FK522A796BD15ADD11`;
ALTER TABLE `pdpdescriptor` ADD INDEX `FK522A796B37AB64C2` USING BTREE (entity_descriptor_id);
ALTER TABLE `pdpdescriptor` ADD CONSTRAINT `FK522A796B37AB64C2` FOREIGN KEY (`entity_descriptor_id`) REFERENCES `entity_descriptor` (`id`);
ALTER TABLE `pdpdescriptor_nameidformats` DROP FOREIGN KEY `FKBE823BE2B6E7D72A`;
ALTER TABLE `pdpdescriptor_nameidformats` DROP INDEX `FKBE823BE2B6E7D72A`;
ALTER TABLE `pdpdescriptor_nameidformats` ADD INDEX `FKBE823BE27F46D519` USING BTREE (pdpdescriptor_id);
ALTER TABLE `pdpdescriptor_nameidformats` ADD CONSTRAINT `FKBE823BE27F46D519` FOREIGN KEY (`pdpdescriptor_id`) REFERENCES `pdpdescriptor` (`id`);
ALTER TABLE `permission` DROP FOREIGN KEY `FKE125C5CFAA6DB197`;
ALTER TABLE `permission` DROP FOREIGN KEY `FKE125C5CF42555646`;
ALTER TABLE `permission` DROP FOREIGN KEY `FKE125C5CF35C9368E`;
ALTER TABLE `permission` DROP INDEX `FKE125C5CF35C9368E`;
ALTER TABLE `permission` DROP INDEX `FKE125C5CFAA6DB197`;
ALTER TABLE `permission` DROP INDEX `FKE125C5CF42555646`;
ALTER TABLE `permission` DROP COLUMN `group_id`;
ALTER TABLE `permission` ADD COLUMN `subject_id` bigint(20) DEFAULT NULL after `role_id`;
ALTER TABLE `permission` DROP COLUMN `user_id`;
ALTER TABLE `permission` CHANGE COLUMN `class` `class` varchar(255) CHARACTER SET latin1 NOT NULL after `type`;
ALTER TABLE `permission` ENGINE=`InnoDB` AUTO_INCREMENT=4 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `permission` ADD INDEX `FKE125C5CFF1ED9519` USING BTREE (subject_id);
ALTER TABLE `permission` ADD INDEX `FKE125C5CF127187CC` USING BTREE (role_id);
ALTER TABLE `permission` ADD CONSTRAINT `FKE125C5CF127187CC` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`);
ALTER TABLE `permission` ADD CONSTRAINT `FKE125C5CFF1ED9519` FOREIGN KEY (`subject_id`) REFERENCES `subject_base` (`id`);
ALTER TABLE `process` DROP FOREIGN KEY `FKED8D1E6F81BFCA4C`;
ALTER TABLE `process` DROP FOREIGN KEY `FKED8D1E6F569B596`;
ALTER TABLE `process` DROP INDEX `FKED8D1E6F569B596`;
ALTER TABLE `process` DROP INDEX `FKED8D1E6F81BFCA4C`;
ALTER TABLE `process` ENGINE=`InnoDB` AUTO_INCREMENT=5 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `process` ADD INDEX `FKED8D1E6FAB057DDA` USING BTREE (last_editor_id);
ALTER TABLE `process` ADD INDEX `FKED8D1E6F2EAF6924` USING BTREE (creator_id);
ALTER TABLE `process` ADD CONSTRAINT `FKED8D1E6F2EAF6924` FOREIGN KEY (`creator_id`) REFERENCES `subject_base` (`id`);
ALTER TABLE `process` ADD CONSTRAINT `FKED8D1E6FAB057DDA` FOREIGN KEY (`last_editor_id`) REFERENCES `subject_base` (`id`);
ALTER TABLE `process_instance` DROP FOREIGN KEY `FKAEA874655190F52A`;
ALTER TABLE `process_instance` DROP INDEX `FKAEA874655190F52A`;
ALTER TABLE `process_instance` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `process_instance` ADD INDEX `FKAEA8746596A61F45` USING BTREE (process_id);
ALTER TABLE `process_instance` ADD CONSTRAINT `FKAEA8746596A61F45` FOREIGN KEY (`process_id`) REFERENCES `process` (`id`);
CREATE TABLE `role` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `protect` bit(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE `name` USING BTREE (`name`)) ENGINE=`InnoDB` AUTO_INCREMENT=4 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `role_descriptor` DROP FOREIGN KEY `FKAF7FE2D8E5FA11AA`;
ALTER TABLE `role_descriptor` DROP FOREIGN KEY `FKAF7FE2D84B267440`;
ALTER TABLE `role_descriptor` DROP INDEX `FKAF7FE2D84B267440`;
ALTER TABLE `role_descriptor` DROP INDEX `FKAF7FE2D8E5FA11AA`;
ALTER TABLE `role_descriptor` CHANGE COLUMN `archived` `archived` bit(1) NOT NULL after `approved`;
ALTER TABLE `role_descriptor` CHANGE COLUMN `description` `description` varchar(2000) CHARACTER SET latin1 NOT NULL after `date_created`;
ALTER TABLE `role_descriptor` ADD COLUMN `errorurl` varchar(255) CHARACTER SET latin1 DEFAULT NULL after `display_name`;
ALTER TABLE `role_descriptor` DROP COLUMN `errorurl_id`;
ALTER TABLE `role_descriptor` CHANGE COLUMN `extensions` `extensions` varchar(2000) CHARACTER SET latin1 DEFAULT NULL after `errorurl`;
ALTER TABLE `role_descriptor` ADD INDEX `FKAF7FE2D899DC19DB` USING BTREE (organization_id);
ALTER TABLE `role_descriptor` ADD CONSTRAINT `FKAF7FE2D899DC19DB` FOREIGN KEY (`organization_id`) REFERENCES `organization` (`id`);
ALTER TABLE `role_descriptor_samluri` DROP FOREIGN KEY `FK3FF0C378891B7F3`;
ALTER TABLE `role_descriptor_samluri` DROP FOREIGN KEY `FK3FF0C3783688E26A`;
ALTER TABLE `role_descriptor_samluri` DROP INDEX `FK3FF0C378891B7F3`;
ALTER TABLE `role_descriptor_samluri` DROP INDEX `FK3FF0C3783688E26A`;
ALTER TABLE `role_descriptor_samluri` ADD INDEX `FK3FF0C378F9BCBF99` USING BTREE (samluri_id);
ALTER TABLE `role_descriptor_samluri` ADD INDEX `FK3FF0C3784C1277E4` USING BTREE (role_descriptor_protocol_support_enumerations_id);
ALTER TABLE `role_descriptor_samluri` ADD CONSTRAINT `FK3FF0C3784C1277E4` FOREIGN KEY (`role_descriptor_protocol_support_enumerations_id`) REFERENCES `role_descriptor` (`id`);
ALTER TABLE `role_descriptor_samluri` ADD CONSTRAINT `FK3FF0C378F9BCBF99` FOREIGN KEY (`samluri_id`) REFERENCES `samluri` (`id`);
CREATE TABLE `role_subjects` (
  `role_id` bigint(20) NOT NULL,
  `subject_base_id` bigint(20) NOT NULL,
  PRIMARY KEY (`role_id`, `subject_base_id`),
  INDEX `FK47DA2670127187CC` USING BTREE (role_id),
  INDEX `FK47DA26708235541` USING BTREE (subject_base_id),
  CONSTRAINT `FK47DA2670127187CC` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`),
  CONSTRAINT `FK47DA26708235541` FOREIGN KEY (`subject_base_id`) REFERENCES `subject_base` (`id`)) ENGINE=`InnoDB` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `samluri` CHANGE COLUMN `id` `id` bigint(20) NOT NULL AUTO_INCREMENT first;
ALTER TABLE `samluri` ADD COLUMN `version` bigint(20) NOT NULL after `id`;
ALTER TABLE `samluri` ADD COLUMN `description` varchar(255) CHARACTER SET latin1 DEFAULT NULL after `version`;
ALTER TABLE `samluri` CHANGE COLUMN `type` `type` varchar(255) CHARACTER SET latin1 NOT NULL after `description`;
ALTER TABLE `samluri` ADD COLUMN `uri` varchar(255) CHARACTER SET latin1 NOT NULL after `type`;
ALTER TABLE `samluri` ENGINE=`InnoDB` AUTO_INCREMENT=27 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `service_category` ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `service_description` ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `service_monitor` DROP FOREIGN KEY `FK1BC0A5D03E6B7924`;
ALTER TABLE `service_monitor` DROP FOREIGN KEY `FK1BC0A5D013FAB137`;
ALTER TABLE `service_monitor` DROP INDEX `FK1BC0A5D03E6B7924`;
ALTER TABLE `service_monitor` DROP INDEX `FK1BC0A5D013FAB137`;
ALTER TABLE `service_monitor` CHANGE COLUMN `node` `node` varchar(255) CHARACTER SET latin1 DEFAULT NULL after `enabled`;
ALTER TABLE `service_monitor` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `service_monitor` ADD INDEX `FK1BC0A5D0577B7128` USING BTREE (role_descriptor_id);
ALTER TABLE `service_monitor` ADD INDEX `FK1BC0A5D05CFF26D3` USING BTREE (type_id);
ALTER TABLE `service_monitor` ADD CONSTRAINT `FK1BC0A5D0577B7128` FOREIGN KEY (`role_descriptor_id`) REFERENCES `role_descriptor` (`id`);
ALTER TABLE `service_monitor` ADD CONSTRAINT `FK1BC0A5D05CFF26D3` FOREIGN KEY (`type_id`) REFERENCES `monitor_type` (`id`);
CREATE TABLE `session_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `credential` varchar(255) NOT NULL,
  `date_created` datetime NOT NULL,
  `remote_host` varchar(255) NOT NULL,
  `subject_id` bigint(20) NOT NULL,
  `user_agent` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK701FF21AF1ED9519` USING BTREE (subject_id),
  CONSTRAINT `FK701FF21AF1ED9519` FOREIGN KEY (`subject_id`) REFERENCES `subject_base` (`id`)) ENGINE=`InnoDB` AUTO_INCREMENT=2 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `single_logout_service` DROP FOREIGN KEY `FKB20C29D7C6661FF9`;
ALTER TABLE `single_logout_service` DROP INDEX `FKB20C29D7C6661FF9`;
ALTER TABLE `single_logout_service` ADD INDEX `FKB20C29D78EC51DE8` USING BTREE (descriptor_id);
ALTER TABLE `single_logout_service` ADD CONSTRAINT `FKB20C29D78EC51DE8` FOREIGN KEY (`descriptor_id`) REFERENCES `ssodescriptor` (`id`);
ALTER TABLE `single_sign_on_service` DROP FOREIGN KEY `FK811EE62081D2AAE4`;
ALTER TABLE `single_sign_on_service` DROP INDEX `FK811EE62081D2AAE4`;
ALTER TABLE `single_sign_on_service` ADD INDEX `FK811EE620E8233295` USING BTREE (descriptor_id);
ALTER TABLE `single_sign_on_service` ADD CONSTRAINT `FK811EE620E8233295` FOREIGN KEY (`descriptor_id`) REFERENCES `idpssodescriptor` (`id`);
ALTER TABLE `spssodescriptor` DROP FOREIGN KEY `FK2AD07B81D15ADD11`;
ALTER TABLE `spssodescriptor` DROP FOREIGN KEY `FK2AD07B814337A9DF`;
ALTER TABLE `spssodescriptor` DROP INDEX `FK2AD07B81D15ADD11`;
ALTER TABLE `spssodescriptor` DROP INDEX `FK2AD07B814337A9DF`;
ALTER TABLE `spssodescriptor` ADD INDEX `FK2AD07B8157850950` USING BTREE (service_description_id);
ALTER TABLE `spssodescriptor` ADD INDEX `FK2AD07B8137AB64C2` USING BTREE (entity_descriptor_id);
ALTER TABLE `spssodescriptor` ADD CONSTRAINT `FK2AD07B8137AB64C2` FOREIGN KEY (`entity_descriptor_id`) REFERENCES `entity_descriptor` (`id`);
ALTER TABLE `spssodescriptor` ADD CONSTRAINT `FK2AD07B8157850950` FOREIGN KEY (`service_description_id`) REFERENCES `service_description` (`id`);
ALTER TABLE `spssodescriptor_service_category` DROP FOREIGN KEY `FK56511C469F5860A7`;
ALTER TABLE `spssodescriptor_service_category` DROP FOREIGN KEY `FK56511C462510C975`;
ALTER TABLE `spssodescriptor_service_category` DROP INDEX `FK56511C462510C975`;
ALTER TABLE `spssodescriptor_service_category` DROP INDEX `FK56511C469F5860A7`;
ALTER TABLE `spssodescriptor_service_category` ADD INDEX `FK56511C46CBEF9ED6` USING BTREE (spssodescriptor_service_categories_id);
ALTER TABLE `spssodescriptor_service_category` ADD INDEX `FK56511C4651A807A4` USING BTREE (service_category_id);
ALTER TABLE `spssodescriptor_service_category` ADD CONSTRAINT `FK56511C4651A807A4` FOREIGN KEY (`service_category_id`) REFERENCES `service_category` (`id`);
ALTER TABLE `spssodescriptor_service_category` ADD CONSTRAINT `FK56511C46CBEF9ED6` FOREIGN KEY (`spssodescriptor_service_categories_id`) REFERENCES `spssodescriptor` (`id`);
ALTER TABLE `ssodescriptor_samluri` DROP FOREIGN KEY `FKBF8D255ED6875DB3`;
ALTER TABLE `ssodescriptor_samluri` DROP FOREIGN KEY `FKBF8D255E3688E26A`;
ALTER TABLE `ssodescriptor_samluri` DROP INDEX `FKBF8D255ED6875DB3`;
ALTER TABLE `ssodescriptor_samluri` DROP INDEX `FKBF8D255E3688E26A`;
ALTER TABLE `ssodescriptor_samluri` ADD INDEX `FKBF8D255EF9BCBF99` USING BTREE (samluri_id);
ALTER TABLE `ssodescriptor_samluri` ADD INDEX `FKBF8D255E9EE65BA2` USING BTREE (ssodescriptor_nameidformats_id);
ALTER TABLE `ssodescriptor_samluri` ADD CONSTRAINT `FKBF8D255E9EE65BA2` FOREIGN KEY (`ssodescriptor_nameidformats_id`) REFERENCES `ssodescriptor` (`id`);
ALTER TABLE `ssodescriptor_samluri` ADD CONSTRAINT `FKBF8D255EF9BCBF99` FOREIGN KEY (`samluri_id`) REFERENCES `samluri` (`id`);
CREATE TABLE `subject_base` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `enabled` bit(1) NOT NULL,
  `principal` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `cn` varchar(255) DEFAULT NULL,
  `contact_id` bigint(20) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `shared_token` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE `principal` USING BTREE (principal),
  INDEX `FKA600C60486998819` USING BTREE (contact_id),
  CONSTRAINT `FKA600C60486998819` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`id`)) ENGINE=`InnoDB` AUTO_INCREMENT=3 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `task` DROP FOREIGN KEY `FK3635855190F52A`;
ALTER TABLE `task` DROP INDEX `FK3635855190F52A`;
ALTER TABLE `task` ENGINE=`InnoDB` AUTO_INCREMENT=24 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `task` ADD INDEX `FK36358596A61F45` USING BTREE (process_id);
ALTER TABLE `task` ADD CONSTRAINT `FK36358596A61F45` FOREIGN KEY (`process_id`) REFERENCES `process` (`id`);
ALTER TABLE `task_dependencies` DROP FOREIGN KEY `FK6B2811A3C4B34BCA`;
ALTER TABLE `task_dependencies` DROP INDEX `FK6B2811A3C4B34BCA`;
ALTER TABLE `task_dependencies` ADD INDEX `FK6B2811A3E1E4CF8F` USING BTREE (task_id);
ALTER TABLE `task_dependencies` ADD CONSTRAINT `FK6B2811A3E1E4CF8F` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`);
ALTER TABLE `task_instance` DROP FOREIGN KEY `FK2198F60FDD269C5D`;
ALTER TABLE `task_instance` DROP FOREIGN KEY `FK2198F60FC4B34BCA`;
ALTER TABLE `task_instance` DROP FOREIGN KEY `FK2198F60F4FC59D29`;
ALTER TABLE `task_instance` DROP INDEX `FK2198F60FC4B34BCA`;
ALTER TABLE `task_instance` DROP INDEX `FK2198F60FDD269C5D`;
ALTER TABLE `task_instance` DROP INDEX `FK2198F60F4FC59D29`;
ALTER TABLE `task_instance` ENGINE=`InnoDB` AUTO_INCREMENT=1 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `task_instance` ADD INDEX `FK2198F60F8D487C44` USING BTREE (process_instance_id);
ALTER TABLE `task_instance` ADD INDEX `FK2198F60F66C4FEB` USING BTREE (approver_id);
ALTER TABLE `task_instance` ADD INDEX `FK2198F60FE1E4CF8F` USING BTREE (task_id);
ALTER TABLE `task_instance` ADD CONSTRAINT `FK2198F60F66C4FEB` FOREIGN KEY (`approver_id`) REFERENCES `subject_base` (`id`);
ALTER TABLE `task_instance` ADD CONSTRAINT `FK2198F60F8D487C44` FOREIGN KEY (`process_instance_id`) REFERENCES `process_instance` (`id`);
ALTER TABLE `task_instance` ADD CONSTRAINT `FK2198F60FE1E4CF8F` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`);
CREATE TABLE `task_instance_subject` (
  `task_instance_potential_approvers_id` bigint(20) DEFAULT NULL,
  `subject_id` bigint(20) DEFAULT NULL,
  INDEX `FK997F72FCBA477424` USING BTREE (subject_id),
  INDEX `FK997F72FC4379238C` USING BTREE (task_instance_potential_approvers_id),
  CONSTRAINT `FK997F72FC4379238C` FOREIGN KEY (`task_instance_potential_approvers_id`) REFERENCES `task_instance` (`id`),
  CONSTRAINT `FK997F72FCBA477424` FOREIGN KEY (`subject_id`) REFERENCES `subject_base` (`id`)) ENGINE=`InnoDB` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `task_outcome` DROP FOREIGN KEY `FKE75A8E98C4B34BCA`;
ALTER TABLE `task_outcome` DROP INDEX `FKE75A8E98C4B34BCA`;
ALTER TABLE `task_outcome` ENGINE=`InnoDB` AUTO_INCREMENT=22 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `task_outcome` ADD INDEX `FKE75A8E98E1E4CF8F` USING BTREE (task_id);
ALTER TABLE `task_outcome` ADD CONSTRAINT `FKE75A8E98E1E4CF8F` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`);
ALTER TABLE `task_rejection` DROP FOREIGN KEY `FKAB7159CFC4B34BCA`;
ALTER TABLE `task_rejection` DROP INDEX `FKAB7159CFC4B34BCA`;
ALTER TABLE `task_rejection` ENGINE=`InnoDB` AUTO_INCREMENT=12 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `task_rejection` ADD INDEX `FKAB7159CFE1E4CF8F` USING BTREE (task_id);
ALTER TABLE `task_rejection` ADD CONSTRAINT `FKAB7159CFE1E4CF8F` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`);
ALTER TABLE `wayf_access_record` CHANGE COLUMN `idp_entity` `idp_entity` varchar(255) CHARACTER SET latin1 NOT NULL after `ds_host`;
ALTER TABLE `wayf_access_record` CHANGE COLUMN `sp_endpoint` `sp_endpoint` varchar(255) CHARACTER SET latin1 NOT NULL after `source`;
ALTER TABLE `wayf_access_record` ENGINE=`InnoDB` AUTO_INCREMENT=2095 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `workflow_message` DROP FOREIGN KEY `FK94DE4F87569B596`;
ALTER TABLE `workflow_message` DROP FOREIGN KEY `FK94DE4F875221BAB5`;
ALTER TABLE `workflow_message` DROP FOREIGN KEY `FK94DE4F874FC59D29`;
ALTER TABLE `workflow_message` DROP INDEX `FK94DE4F875221BAB5`;
ALTER TABLE `workflow_message` DROP INDEX `FK94DE4F87569B596`;
ALTER TABLE `workflow_message` DROP INDEX `FK94DE4F874FC59D29`;
ALTER TABLE `workflow_message` ADD INDEX `FK94DE4F878D487C44` USING BTREE (process_instance_id);
ALTER TABLE `workflow_message` ADD INDEX `FK94DE4F872EAF6924` USING BTREE (creator_id);
ALTER TABLE `workflow_message` ADD INDEX `FK94DE4F87CBC9A97A` USING BTREE (task_instance_id);
ALTER TABLE `workflow_message` ADD CONSTRAINT `FK94DE4F872EAF6924` FOREIGN KEY (`creator_id`) REFERENCES `subject_base` (`id`);
ALTER TABLE `workflow_message` ADD CONSTRAINT `FK94DE4F878D487C44` FOREIGN KEY (`process_instance_id`) REFERENCES `process_instance` (`id`);
ALTER TABLE `workflow_message` ADD CONSTRAINT `FK94DE4F87CBC9A97A` FOREIGN KEY (`task_instance_id`) REFERENCES `task_instance` (`id`);
ALTER TABLE `workflow_script` DROP FOREIGN KEY `FK828A914B81BFCA4C`;
ALTER TABLE `workflow_script` DROP FOREIGN KEY `FK828A914B569B596`;
ALTER TABLE `workflow_script` DROP INDEX `FK828A914B569B596`;
ALTER TABLE `workflow_script` DROP INDEX `FK828A914B81BFCA4C`;
ALTER TABLE `workflow_script` ENGINE=`InnoDB` AUTO_INCREMENT=12 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ROW_FORMAT=COMPACT CHECKSUM=0 DELAY_KEY_WRITE=0;
ALTER TABLE `workflow_script` ADD INDEX `FK828A914BAB057DDA` USING BTREE (last_editor_id);
ALTER TABLE `workflow_script` ADD INDEX `FK828A914B2EAF6924` USING BTREE (creator_id);
ALTER TABLE `workflow_script` ADD CONSTRAINT `FK828A914B2EAF6924` FOREIGN KEY (`creator_id`) REFERENCES `subject_base` (`id`);
ALTER TABLE `workflow_script` ADD CONSTRAINT `FK828A914BAB057DDA` FOREIGN KEY (`last_editor_id`) REFERENCES `subject_base` (`id`);
SET FOREIGN_KEY_CHECKS = 1;
